language: node_js
node_js: 8
cache:
  yarn: true
  directories:
  - node_modules
  - "${NVM_PATH}_modules"
install:
- yarn
- cd functions && yarn && cd ..
script:
- yarn lint
- echo "Building..."
- if [ "$TRAVIS_BRANCH" == "develop" ]; then yarn build; fi
- if [ "$TRAVIS_BRANCH" == "master" ]; then yarn build:prod; fi
before_deploy:
- echo "Deploying!"
deploy:
- provider: firebase
  skip_cleanup: true
  on:
    branch: master
  project: mobileera-2018
  token:
    secure: MZ7yl9WNQJsmM1pUkfDzUEEdH0fnM44tysgCg4NZcCiCqOBkZgygUNQOxh2CILxCxpHaiebNJw3nLfKBCxtt1wM3ezFZdvWUghrl/yhC5y5Bpt7S5IlHRrsuajEaBZ/aGlztRb9lr16pAO+VQI1Cps3zTekc7bZOARMRqCGfBEGuQJ4ehDuB+d3YwIwkKSu208cHBsQz+Z4RSqFN+7GDWLa8Q0I8V1KYm4y7IV9twuCmV66WVazJBMTKCBCOBH8Ej/kOfwz32+EoUZVu+HThwsZMcNw3YC9e8WvfPoahlVddm2AVv3PrrN1OnCTo7VRkk4xCKV6YJGCRitKp9uSLiHS1JG6SqfNJkHMBjBt+lZ9KVIhLcIEOi6CVNAtvcnLYmaTs1AH6tVJECjS27ORNAWUbvn7T1ed68gPSHpf5jok1kBmXGJsDYs5yxgyzaQ9G80DmtVOdNZBYw6UG+H3vkgtUp+t115XJFMnHaee4GqSOoJEoe0eeAF69hinsMsrf3vMkHXCdsc9GXzr3KDgaMe/DJk0h9CGok1WIOdbEH1JOx4i/CXE1RhzUMXhThBpc2+fJS2TsnHhcBXMXyVSDmuJSkhiZ+KNeax2YiU77QbWIjYUGp1hONXjC9XFsEvQYfh9Jn/+K+h9VsyOlxMNTlqlcOLttZYP92+3ChuUHjtw=