language: node_js
node_js: 8
cache:
  yarn: true
  directories:
  - node_modules
  - "${NVM_PATH}_modules"
install:
- yarn
- cd functions && yarn && cd ..
script:
- yarn lint
- echo "Building..."
- if [ "$TRAVIS_BRANCH" == "develop" ]; then yarn build; fi
- if [ "$TRAVIS_BRANCH" == "master" ]; then yarn build:prod; fi
before_deploy:
- echo "Deploying!"
deploy:
- provider: firebase
  skip_cleanup: true
  on:
    branch: master
  project: mobileera-2018
  token:
    secure: mDvQoZ/exd59cNBzswn7mXkT8CnbfkjzvgnzCLqEozFa/iNXJoZh/0YuLmjTP1f0Q6gkOmjHZJFOU+bkRVyQ8oHIVBpmVES2qwtLxqo+usU+wJcfRq2NC/O8pAtWnVe9zoND2wLB7ClRUbiQxz1byiCtpIJLlKvglYqEb8pLG822LuW6WT+ETIlnIbs9IJX6xorLP6ssPkyxQqo0ypo0hIKx52J3/aPLpQuXMkKRPGM/uLQu/f9FornJzfapp6xOmIwLPIkre1Feb0lKQ/GmUGFKV20e8xKd0l6/y68rZq2NxUUQYchf8qP1G8ojBEgDuhKCn31Rqfpa2JIq9+QuI66UJ4l8feRMkes2awtlpMLc4d7srlSPqUbgoKnU2vs8irXxSifw0tnRnXJK9aqQoEVc8WZ8yQPoSF1gHQEEezAFhEXRQeimMveig+DmA5WnPse46V/mNjyFPcqlp5Os0FQhB2Ls6GoeziXBK3pOodeg/vEaglv5caAg4OIETEa/JyU1UqS0MIVJm9b06I/0cXZ8noomT6bLIB7NdW6eZ5+hwNbpP6QtSA7LUOmf5hlq0WJL0wXmuMrHWIDtENMeg+cz90Km5dENuJtstQEahlHD9onhtJV/lBNEU2znWvDTLaI8ZzG98s+ISyDnfG+dyMu2v/2aRYmqYZJJC3SRVDM=